[package]
name = "parabuild"
version = "0.1.0"
edition = "2021"
default-run = "parabuild"

[dependencies]
fs_extra = "1.3.0"
ignore = "0.4"
serial_test = "0.5"
handlebars = "6"
serde_json = "1.0"
crossbeam-channel = "0.5"

[lib]
name = "parabuild"
path = "src/lib.rs"

[[bin]]
name = "parabuild"
path = "src/main.rs"