name: Rust CI

on: [push, pull_request]

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo Test
        run: cargo test --all-features
      - name: Release Build
        run: cargo build --release
      - name: ctrl-c test
        run: ./tests/ctrl-c_test.sh
      - name: autosave test
        run: ./tests/autosave_test.sh