name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build project
      run: cargo build --release

    - name: Extract CHANGELOG for version
      id: changelog
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        version=${VERSION#v}
        CHANGELOG_CONTENT=$(printf "What's Changed\n\n-------------\n\n"; awk -v ver="$version" '
          BEGIN { flag=0 }
          $0 ~ "^# " ver {flag=1; next}
          /^#/ {flag=0}
          flag && NF
        ' CHANGELOG.md)
        echo "$CHANGELOG_CONTENT" > current_version_changelog.md

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: current_version_changelog.md
        files: target/release/parabuild
        prerelease: false
        draft: false